name: Check Code Style

on: workflow_dispatch
  # pull_request:
  #     types: [edited]
  #     branches: [main]

jobs:
  clang-format-check:
    name: Check formatting
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull clang-format
        run: |
          sudo add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main'
          wget https://apt.llvm.org/llvm-snapshot.gpg.key
          sudo apt-key add llvm-snapshot.gpg.key
          sudo apt-get update
          sudo apt-get install -y clang-format-18
      - name: Run clang format
        run: |
          set +e
          git diff -U0 origin/$GITHUB_BASE_REF...HEAD | clang-format-diff-18 -p 1 
  
  # valgrind-check:
  #   runs-on: ubuntu-latest
  #   name: Run valgrind
  #   continue-on-error: true

